# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron: "1 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: curl 'http://bbs.weibufengge.com/plugin.php?id=dsu_paulsign:sign&operation=qiandao&infloat=1&inajax=1' -H 'Proxy-Connection:keep-alive' -H 'Cache-Control:max-age=0' -H 'Origin:http://bbs.weibufengge.com' -H 'Upgrade-Insecure-Requests:1' -H 'DNT:1' -H 'Content-Type:application/x-www-form-urlencoded' -H 'User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36' -H 'Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H 'Referer:http://bbs.weibufengge.com/plugin.php?id=dsu_paulsign:sign' -H 'Accept-Language:zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-TW;q=0.5,uk;q=0.4,ko;q=0.3,sv;q=0.2' -H 'Cookie:PSPH_2132_saltkey=ZPRj21RR; PSPH_2132_lastvisit=1582598103; PSPH_2132_auth=11e7o5G1HX%2BDKmGZkyw5EpMiaCWNt1lOcA5IpqTs%2FVoytIzTT7j%2Fj%2BcANp0r99Tc5xXGXTqsr9jvfnQhb2gmXelfAg; PSPH_2132_lastcheckfeed=11333%7C1582601707; PSPH_2132_connect_is_bind=0; PSPH_2132_nofavfid=1; PSPH_2132_taskdoing_11333=1; PHPSESSID=md129ddfou15jd8gb2k72treq6; PSPH_2132_smile=325D1; PSPH_2132_st_t=11333%7C1583401898%7Cc45045f8e1a04d53a162a36e91091f87; PSPH_2132_forum_lastvisit=D_7_1583401898; PSPH_2132_visitedfid=7D15D73; PSPH_2132_st_p=11333%7C1583402013%7Cedd0be91ec9f868ba8b5723829e21988; PSPH_2132_viewid=tid_246416; PSPH_2132_ulastactivity=40de1pv96mQwiKBnnvDCo5RfIYww2dhBRgGG4Ow815iKIcLxRV1B; PSPH_2132_sendmail=1; PSPH_2132_checkpm=1; PSPH_2132_lip=218.80.1.99%2C1583468208; PSPH_2132_sid=b8v569; PSPH_2132_lastact=1583468208%09misc.php%09patch' --data 'formhash=2fb9216b&qdxq=kx&qdmode=1&todaysay=%BD%F1%CC%EC%D7%EE%CF%EB%CB%B5&fastreply=0' --compressed --insecure 
